[features]
seeds = false
[programs.localnet]
solana_global_article = "zaR6MXmj1DjeCdNBix6R6CA53H6rRXRoiBh4LEAvP2G"
[programs.devnet]
solana_global_article = "zaR6MXmj1DjeCdNBix6R6CA53H6rRXRoiBh4LEAvP2G"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
